name: Build and test
on:
  push:
    branches: main
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install latest stable
        uses: dtolnay/rust-toolchain@stable
      - name: Set up caching of the build
        uses: Swatinem/rust-cache@v2
      - name: Run cargo check
        run: cargo check
      - name: Run cargo build
        run: cargo build
